### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by AndrewKralovec** [pawats/angular2-express-webpack#2]
Yeah, sorry this was the correct Repo
I downloaded your repo, did npm install. However, when i run npm start to test it out i get

70% 3/3 build modulesevents.js:160
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE 127.0.0.1:8080
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at Server._listen2 (net.js:1253:14)
at listen (net.js:1289:10)
at net.js:1399:9
at GetAddrInfoReqWrap.asyncCallback as callback
at GetAddrInfoReqWrap.onlookup as oncomplete

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack@1.0.0 start: webpack-dev-server --inline --progress --port 8080
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack@1.0.0 start script 'webpack-dev-server --inline --progress --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! webpack-dev-server --inline --progress --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs angular2-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls angular2-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by AndrewKralovec** [comment]
Fixed when i switched port
